apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
        - name: hello
          image: k8smysql
          ports:
            - containerPort:  3306
          env:
            - name: MYSQL_SERVICE_HOST
              value:  "mysql"
            - name: MYSQL_SERVICE_PORT
              value:  "3306"