apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort:  3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value:  "123456"