// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package daymenu_shippping_api_container

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/micro/go-micro/api/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbf, 0x6a, 0xc3, 0x30,
	0x10, 0xc6, 0x4b, 0xeb, 0x9a, 0xa2, 0xa5, 0x45, 0xd0, 0xc5, 0x4b, 0xa1, 0x63, 0x5b, 0x4b, 0xd0,
	0x3c, 0x42, 0x86, 0x10, 0xc8, 0x10, 0x02, 0x7e, 0x00, 0xd9, 0xbe, 0xc8, 0x37, 0x58, 0x77, 0xd1,
	0x9f, 0x21, 0xef, 0x92, 0x87, 0x0d, 0x96, 0x87, 0xac, 0x5a, 0x8e, 0xef, 0x8e, 0xdf, 0xf7, 0xc1,
	0x7d, 0xe2, 0x93, 0x3d, 0x45, 0xd2, 0x29, 0x80, 0xcf, 0x43, 0xe5, 0x5d, 0x7e, 0x8d, 0xe6, 0x3a,
	0x83, 0x4b, 0x2a, 0x4c, 0xc8, 0xcc, 0xe8, 0xac, 0x32, 0x8c, 0x6a, 0x20, 0x17, 0x0d, 0x3a, 0xf0,
	0x4d, 0x6b, 0x31, 0x4e, 0xa9, 0x57, 0x03, 0xcd, 0x7a, 0xc6, 0xc1, 0x93, 0xb6, 0xd4, 0xae, 0xc2,
	0x30, 0xea, 0x35, 0x75, 0xb1, 0x64, 0xf5, 0x7f, 0x7b, 0x16, 0x55, 0x17, 0xc0, 0xcb, 0x5f, 0x51,
	0x1d, 0x8d, 0x05, 0xf9, 0xae, 0x2c, 0xe5, 0xc8, 0x13, 0x5c, 0x12, 0x84, 0xd8, 0x7c, 0x3c, 0x0e,
	0x81, 0xc9, 0x05, 0xf8, 0x7e, 0x92, 0x3f, 0xe2, 0x65, 0x07, 0xb1, 0x8c, 0x6d, 0x45, 0xbd, 0xf5,
	0x60, 0x22, 0x14, 0xe3, 0x1d, 0x8f, 0xc5, 0xf8, 0x9f, 0x78, 0x3d, 0x90, 0x45, 0x57, 0x46, 0x6b,
	0xf1, 0xb6, 0x3c, 0xbb, 0x77, 0x67, 0x2a, 0x32, 0xf4, 0x75, 0x6e, 0x69, 0x73, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0xab, 0x97, 0x82, 0xf7, 0x8e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserClient interface {
	Page(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
	Get(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
	Create(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
	Update(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
	Login(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
	UserInfo(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
}

type userClient struct {
	c           client.Client
	serviceName string
}

func NewUserClient(serviceName string, c client.Client) UserClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "daymenu.shippping.api.container"
	}
	return &userClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userClient) Page(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.serviceName, "User.Page", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Get(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.serviceName, "User.Get", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Create(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.serviceName, "User.Create", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Update(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.serviceName, "User.Update", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.serviceName, "User.Login", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserInfo(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.serviceName, "User.UserInfo", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Page(context.Context, *proto1.Request, *proto1.Response) error
	Get(context.Context, *proto1.Request, *proto1.Response) error
	Create(context.Context, *proto1.Request, *proto1.Response) error
	Update(context.Context, *proto1.Request, *proto1.Response) error
	Login(context.Context, *proto1.Request, *proto1.Response) error
	UserInfo(context.Context, *proto1.Request, *proto1.Response) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&User{hdlr}, opts...))
}

type User struct {
	UserHandler
}

func (h *User) Page(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.UserHandler.Page(ctx, in, out)
}

func (h *User) Get(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.UserHandler.Get(ctx, in, out)
}

func (h *User) Create(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.UserHandler.Create(ctx, in, out)
}

func (h *User) Update(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.UserHandler.Update(ctx, in, out)
}

func (h *User) Login(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.UserHandler.Login(ctx, in, out)
}

func (h *User) UserInfo(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.UserHandler.UserInfo(ctx, in, out)
}
