// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/container/container.proto

package daymenu_shipping_srv_container

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Container struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Height               int64    `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Width                int64    `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Long                 int64    `protobuf:"varint,7,opt,name=long,proto3" json:"long,omitempty"`
	Status               int32    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec6c08f9f0309d9, []int{0}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Container) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Container) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Container) GetLong() int64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Container) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Containers struct {
	Containers           []*Container `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Containers) Reset()         { *m = Containers{} }
func (m *Containers) String() string { return proto.CompactTextString(m) }
func (*Containers) ProtoMessage()    {}
func (*Containers) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec6c08f9f0309d9, []int{1}
}

func (m *Containers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Containers.Unmarshal(m, b)
}
func (m *Containers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Containers.Marshal(b, m, deterministic)
}
func (m *Containers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Containers.Merge(m, src)
}
func (m *Containers) XXX_Size() int {
	return xxx_messageInfo_Containers.Size(m)
}
func (m *Containers) XXX_DiscardUnknown() {
	xxx_messageInfo_Containers.DiscardUnknown(m)
}

var xxx_messageInfo_Containers proto.InternalMessageInfo

func (m *Containers) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Request struct {
	Height               int64        `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width                int64        `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Long                 int64        `protobuf:"varint,3,opt,name=long,proto3" json:"long,omitempty"`
	Page                 int64        `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64        `protobuf:"varint,5,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Id                   int64        `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Containers           []*Container `protobuf:"bytes,8,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec6c08f9f0309d9, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Request) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Request) GetLong() int64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Request) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Response struct {
	Code                 int32        `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Containers           []*Container `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	Container            *Container   `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec6c08f9f0309d9, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Response) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

func init() {
	proto.RegisterType((*Container)(nil), "daymenu.shipping.srv.container.Container")
	proto.RegisterType((*Containers)(nil), "daymenu.shipping.srv.container.Containers")
	proto.RegisterType((*Request)(nil), "daymenu.shipping.srv.container.Request")
	proto.RegisterType((*Response)(nil), "daymenu.shipping.srv.container.Response")
}

func init() { proto.RegisterFile("proto/container/container.proto", fileDescriptor_3ec6c08f9f0309d9) }

var fileDescriptor_3ec6c08f9f0309d9 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x8a, 0xd4, 0x40,
	0x10, 0xb5, 0x93, 0x4c, 0x26, 0x53, 0x0b, 0x22, 0x85, 0x68, 0xb3, 0x07, 0x77, 0x98, 0x8b, 0xf1,
	0x12, 0x61, 0xfd, 0x03, 0xf7, 0x30, 0xec, 0x4d, 0x7a, 0x59, 0x04, 0x3d, 0x0c, 0x31, 0x5d, 0x64,
	0x1a, 0x9d, 0xee, 0x98, 0xee, 0x8c, 0xe8, 0x67, 0xf9, 0x13, 0x82, 0x9f, 0xe2, 0x57, 0x48, 0x7a,
	0x32, 0xbd, 0xc3, 0xb2, 0xb8, 0x2e, 0x43, 0x4e, 0xa9, 0x57, 0xd5, 0xf5, 0x5e, 0xd5, 0xeb, 0x26,
	0x70, 0xd6, 0xb4, 0xc6, 0x99, 0xd7, 0x95, 0xd1, 0xae, 0x54, 0x9a, 0xda, 0x9b, 0xa8, 0xf0, 0x15,
	0x7c, 0x21, 0xcb, 0xef, 0x1b, 0xd2, 0x5d, 0x61, 0xd7, 0xaa, 0x69, 0x94, 0xae, 0x0b, 0xdb, 0x6e,
	0x8b, 0x70, 0x6a, 0xf1, 0x8b, 0xc1, 0xec, 0x62, 0x8f, 0xf0, 0x31, 0x44, 0x4a, 0x72, 0x36, 0x67,
	0x79, 0x2c, 0x22, 0x25, 0xf1, 0x0c, 0x4e, 0xaa, 0xce, 0x3a, 0xb3, 0xa1, 0x76, 0xa5, 0x24, 0x8f,
	0xe6, 0x2c, 0x9f, 0x09, 0xd8, 0xa7, 0x2e, 0x25, 0x3e, 0x83, 0xd4, 0xb4, 0xaa, 0x56, 0x9a, 0xc7,
	0xbe, 0x36, 0x20, 0x7c, 0x0e, 0xd3, 0xce, 0xee, 0x9a, 0x92, 0x5d, 0xa1, 0x87, 0xbb, 0x86, 0x35,
	0xa9, 0x7a, 0xed, 0xf8, 0xc4, 0xab, 0x0c, 0x08, 0x9f, 0xc2, 0xe4, 0x9b, 0x92, 0x6e, 0xcd, 0x53,
	0x9f, 0xde, 0x01, 0x44, 0x48, 0xbe, 0x18, 0x5d, 0xf3, 0xa9, 0x4f, 0xfa, 0xb8, 0x67, 0xb0, 0xae,
	0x74, 0x9d, 0xe5, 0xd9, 0x9c, 0xe5, 0x13, 0x31, 0xa0, 0xc5, 0x7b, 0x80, 0xb0, 0x88, 0xc5, 0x4b,
	0x80, 0xb0, 0xa4, 0xe5, 0x6c, 0x1e, 0xe7, 0x27, 0xe7, 0xaf, 0x8a, 0x7f, 0x9b, 0x51, 0x84, 0x7e,
	0x71, 0xd0, 0xbc, 0xf8, 0xc3, 0x60, 0x2a, 0xe8, 0x6b, 0x47, 0xd6, 0x1d, 0x8c, 0xcf, 0xee, 0x1e,
	0x3f, 0xba, 0x6b, 0xfc, 0xf8, 0x60, 0x7c, 0x84, 0xa4, 0x29, 0x6b, 0xf2, 0xb6, 0xc4, 0xc2, 0xc7,
	0x78, 0x0a, 0x59, 0xff, 0xbd, 0x52, 0x3f, 0x68, 0xb0, 0x25, 0xe0, 0xe1, 0x4a, 0xd2, 0x70, 0x25,
	0x08, 0x89, 0x2e, 0x37, 0xe4, 0x2d, 0x99, 0x09, 0x1f, 0xdf, 0x5a, 0x36, 0x3b, 0x66, 0xd9, 0x9f,
	0x0c, 0x32, 0x41, 0xb6, 0x31, 0xda, 0x52, 0xaf, 0x55, 0x19, 0x49, 0x7e, 0xd7, 0x89, 0xf0, 0xf1,
	0x2d, 0xad, 0xe8, 0x08, 0x2d, 0x5c, 0xc2, 0x2c, 0x20, 0xef, 0xd1, 0x83, 0x98, 0x6e, 0x7a, 0xcf,
	0x7f, 0x27, 0xf0, 0x24, 0x14, 0xae, 0xa8, 0xdd, 0xaa, 0x8a, 0x70, 0x05, 0xe9, 0x45, 0x4b, 0xa5,
	0x23, 0xfc, 0x7f, 0xd2, 0xd3, 0xfc, 0xbe, 0xa3, 0x7b, 0x6f, 0x16, 0x8f, 0x7a, 0x81, 0xeb, 0x46,
	0x8e, 0x28, 0xf0, 0x01, 0xe2, 0x25, 0x39, 0x7c, 0x79, 0x7f, 0x8b, 0x7f, 0x9c, 0x0f, 0xe5, 0xbe,
	0xb6, 0x34, 0x0e, 0xf7, 0x47, 0x48, 0xde, 0xf5, 0xcf, 0x7a, 0x14, 0xf2, 0x15, 0x64, 0x4b, 0xb5,
	0xa5, 0xb7, 0x65, 0xf5, 0x79, 0x14, 0x81, 0x4f, 0xa9, 0xff, 0x71, 0xbe, 0xf9, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xf5, 0x6b, 0x83, 0xce, 0x5b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ContainerService service

type ContainerServiceClient interface {
	Create(ctx context.Context, in *Container, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, in *Container, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Use(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Page(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GiveBack(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type containerServiceClient struct {
	c           client.Client
	serviceName string
}

func NewContainerServiceClient(serviceName string, c client.Client) ContainerServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "daymenu.shipping.srv.container"
	}
	return &containerServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *containerServiceClient) Create(ctx context.Context, in *Container, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ContainerService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) Update(ctx context.Context, in *Container, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ContainerService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ContainerService.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) Use(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ContainerService.Use", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) Page(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ContainerService.Page", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) GiveBack(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ContainerService.GiveBack", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ContainerService service

type ContainerServiceHandler interface {
	Create(context.Context, *Container, *Response) error
	Update(context.Context, *Container, *Response) error
	Get(context.Context, *Request, *Response) error
	Use(context.Context, *Request, *Response) error
	Page(context.Context, *Request, *Response) error
	GiveBack(context.Context, *Request, *Response) error
}

func RegisterContainerServiceHandler(s server.Server, hdlr ContainerServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ContainerService{hdlr}, opts...))
}

type ContainerService struct {
	ContainerServiceHandler
}

func (h *ContainerService) Create(ctx context.Context, in *Container, out *Response) error {
	return h.ContainerServiceHandler.Create(ctx, in, out)
}

func (h *ContainerService) Update(ctx context.Context, in *Container, out *Response) error {
	return h.ContainerServiceHandler.Update(ctx, in, out)
}

func (h *ContainerService) Get(ctx context.Context, in *Request, out *Response) error {
	return h.ContainerServiceHandler.Get(ctx, in, out)
}

func (h *ContainerService) Use(ctx context.Context, in *Request, out *Response) error {
	return h.ContainerServiceHandler.Use(ctx, in, out)
}

func (h *ContainerService) Page(ctx context.Context, in *Request, out *Response) error {
	return h.ContainerServiceHandler.Page(ctx, in, out)
}

func (h *ContainerService) GiveBack(ctx context.Context, in *Request, out *Response) error {
	return h.ContainerServiceHandler.GiveBack(ctx, in, out)
}
